### ISSUE TITLE
Investoscope must be open to import data

### ISSUE THREAD

**Issue by Rod-Persky** [Rod-Persky/investoscope-easy-update#1]
👍 please open investoscope haha... I'll fix this

**Comment by Rod-Persky** [comment]
Well... probably should just add a notification or something

**Comment by Rod-Persky** [comment]
Starting the updater will result in the following error:

`1 b'' b'74:114: execution error: Investoscope 3 got an error: Can\xe2\x80\x99t get document 1. Invalid index. (-1719)\n'`

However macOS appears to launch investoscope?

**Comment by charlietomo** [comment]
FYI I get a similar result to you:
`1 b'' b'74:115: execution error: Investoscope 3 got an error: Can\xe2\x80\x99t get document 1. Invalid index. (-1719)\n'`

And Investoscope opens and continues the update. I'm running the latest version of your program, macOS 10.13.6 and Investoscope 3.0.15. Wasn't generally an issue for me as I remembered to have the program open :-)

**Comment by Rod-Persky** [comment]
Your right, so macOS will open the app if it closes. I also closed the app during the update process which results in macOS opening the app again.

It ranks maybe 5/10 on criticality. macOS is quite smart 👍

**Comment by Rod-Persky** [comment]
Version 2 might benefit from detecting this error and then:

1) waiting for investoscope to open, or
2) asking the user to restart the updater when they are ready and closing

**Comment by Rod-Persky** [comment]
Since AppleScript opens Investoscope, this should be ok.
