### ISSUE TITLE
Update README with module install instructions

### ISSUE THREAD

**Issue by jashsayani** [Rod-Persky/investoscope-easy-update#3]
The script uses some modules and my machines doesnt have them. When I run the script, I see:
`ModuleNotFoundError: No module named 'requests'`

The README file should contain instructions on how to install dependencies / modules used by the script.

**Comment by charlietomo** [comment]
I am no expert but had the same issue and fixed it by running `pip3 install requests`.

**Comment by jashsayani** [comment]
I tried it out but I still see missing modules. Also, it should be in the `README` file.

**Comment by Rod-Persky** [comment]
+1 will fix

**Comment by Rod-Persky** [comment]
👍 sorted
