### ISSUE TITLE
Incorrect data from Yahoo! may cause issues with historical reports

### ISSUE THREAD

**Issue by charlietomo** [Rod-Persky/investoscope-easy-update#5]
Mentioning this here - not as an issue with the script but to draw users attention to an issue with some of Yahoo's data.

Some data from LSE has mixed GBP and GBp quotes - typically GBp for the current quote (so after running script the latest price is upto date) but GBP for the historical data. So this means that any reports done in Investoscope including those instruments are out by a factor of 100 for those instruments!

An wrong share is here: https://finance.yahoo.com/quote/WWH.L/history?p=WWH.L
A correct share is here: https://finance.yahoo.com/quote/VOD.L/history?p=VOD.L

This appears to be a known issue, with [comments from November indicating Yahoo would look into it](https://forums.yahoo.net/t5/Yahoo-Finance-help/Some-securities-traded-on-LSE-posting-Historical-Data-in-both/td-p/415719) but I am still having the issues.

**Comment by Rod-Persky** [comment]
I've added this to the readme @charlietomo to make it clear that there are known problems with data accuracy. To improve this situation, I wonder if you know any end of day quote providers (do you use someone other than yahoo) or maybe you could suggest a rule that could be used to recognise this error?
