### ISSUE TITLE
Does the script update exchange rates

### ISSUE THREAD

**Issue by obyone** [Rod-Persky/investoscope-easy-update#7]
Firstly I would like to say a big thank you for taking the time to create and maintain this.  I love Investoscope and was gutted when it stopped working.  I haven't been able to find anything else that meets my needs.

Does the script update the exchange rates in the application?  I'm in the UK and use GBP but have some foreign shares, mainly US.

**Comment by Rod-Persky** [comment]
Hi @obyone I wish I could put a proxy between Investoscope and the internet to 'pretend' to be yahoo or google and be able to integrate with the normal currency functions. Whilst there is a mechanism in Investoscope to do this, the app protection mechanism makes one of those avenues unavailable.

Good news though, we can still retrieve stock charts as a 'stock' or (in my preference) a 'miscellaneous' entry. Is this something that would be ok? You can see how I've managed this on the attached screenshot.

<img width="598" alt="screen shot 2018-04-21 at 11 37 36 am" src="https://user-images.githubusercontent.com/770327/39079150-6f5407da-4558-11e8-982d-2652386ede29.png">

**Comment by charlietomo** [comment]
@Rod-Persky 
> ... I wish I could put a proxy between Investoscope and the internet to 'pretend' to be yahoo or google and be able to integrate with the normal currency functions.

Do you know what the URL differences are? This is an interesting option to do e.g. at the computer or network level. It would be great to be able to get full history back in Investoscope; I'm finding this method only brings in very recent data and has removed all my historical quotes.

**Comment by Rod-Persky** [comment]
Well if it is possible to proxy the connection, then anything can be done :)

Regarding the historical quotes: I thought investoscope should update the quotes based on what was provided. It is however correct that the script only grabs the last 3 years of quotes.

**Comment by charlietomo** [comment]
I've done a little with [Charles](https://www.charlesproxy.com) recently, an app for proxying. Taking a quick look it might be able to re-write connections on the fly ([see here](https://www.charlesproxy.com/documentation/tools/map-remote/)) but I suspect it is a lot of work to get things going, including trusting certificates etc. I keep my portfolios separated by currency and then can easily see the portfolio gain, and separately work out the FX gain or loss.

**Comment by Rod-Persky** [comment]
I think the solution is to add an entry to the hosts file /etc/hosts to localhost and run a lightweight DNS or FaaS server. It is perhaps not too crazy, but it will require root privileges to modify /etc/hosts whereas the app right now can simply run ad-hock.

**Comment by Rod-Persky** [comment]
(this issue is actually about updating FX, which I think the present approach is OK given the constraints)

We can discuss the proxy thing over in #11 👍
