### ISSUE TITLE
Issue with latest version - no updates, app closes

### ISSUE THREAD

**Issue by charlietomo** [Rod-Persky/investoscope-easy-update#9]
Hi @Rod-Persky I just updated to the latest version you released and it doesn't work on my machine :-(
I updated the .py file with the same path as the previous version. When I run the new app, it opens with a list of shares, saying "up to date:" and then after a few seconds closes. Python doesn't do any connections to the internet.
If I immediately run the older version it cycles through and updates. None of my symbols were up to date.

I can use the old one (but would love the error checking in the new one, as I still get issues with the old one) but am happy to help troubleshoot the new release just let us know what you need. I've got a video of what happens if that helps?

**Comment by charlietomo** [comment]
Just an update. I waited ~17 hours and tried again, and this time the same new version worked. I didn't change any settings at my end - so I'm not really sure what the issue is? It might be on my machine, but I don't really know what if so.

I am happy to try different things but am not sure what I can do. At the moment both updaters seem a bit sporadic. When they work it is great but often they won't update. Appreciate this is a volunteer project so please don't take this as a criticism. Happy to help but just don't know how (as I'm not a coder...).

**Comment by Rod-Persky** [comment]
This behaviour comes down to this line [here](https://github.com/Rod-Persky/investoscope-easy-update/blob/master/Investoscope%20Updater.app/Contents/Resources/update.py#L58). Essentially the update script will only update the data once per day (as history rarely changes). There may be a bug where the update process fails but still changes the date essentially rendering the update process `broken` for a day.

Specifically, if the code gets to [this point](https://github.com/Rod-Persky/investoscope-easy-update/blob/master/Investoscope%20Updater.app/Contents/Resources/update.py#L93) without failing it was assumed that the update succeeded and thus the state (date, and whatever else I need to store between runs) is saved.

**Comment by Rod-Persky** [comment]
Oh, if you really really really get fed up you can go to `~/.investoscope` and delete `state.p` which stores the last update time... it's safe to delete 👍 

<img width="291" alt="delete_state_p" src="https://user-images.githubusercontent.com/770327/44353924-c984e600-a4eb-11e8-80bc-83c5d561eb41.png">

(Yes... I've virtually deleted it a few times 🥇 )
